baseURL = "https://example.com"
title = "Cyber Brain"
theme = "robotico"
paginate = 3

[params]
#description = "A sleek personal website theme"
#logofile = "img/robobrand.png"
#faviconfile = "img/robobrand.png"
#copyright = "Wiley McKay Conte 2018"
#github = "wileybaba"
#email = "baba@example.com"
#fork = "github.com/wileybaba/Robotico_hugo_theme"
progressively = true
defaultContentLanguage = 'en'

# Menus

[languages]
  [languages.en]
  languageCode = "en-us"
    [[languages.en.menu.primary]]
    identifier = "home"
    name = "home"
    url = "//"
    weight = 10

    [[languages.en.menu.primary]]
    identifier = "portfolio"
    name = "portfolio"
    url = "/portfolio/"
    weight = 20

    [[languages.en.menu.primary]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 30


# Gallery 

  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=251"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=252"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=253"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=254"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=255"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=256"
